# Generated by Django 3.0.6 on 2022-04-23 14:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post1',
            name='content',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='post1',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post1',
            name='title',
            field=models.CharField(default='', max_length=30),
        ),
    ]
